import os

HOST = "127.0.0.1"
PORT = 8080
CSRF_ENABLED = True

SECRET_KEY = "secret"
SECURITY_PASSWORD_SALT = 'salt'
SECURITY_PASSQWORD_HASH = 'bcrypt'
SQLALCHEMY_DATABASE_URI = "sqlite:////tmp/db.sql"
SQLALCHEMY_TRACK_MODIFICATIONS = True
